name: Check 365
on:
  schedule:
    - cron: 0 16 * * *
    - cron: 0 20 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - run: |
         go run . -u darmiel \
          -a ${{ secrets.PUSH_APP_KEY }} \
          -r ${{ secrets.PUSH_RECIPIENT_KEY }} \
          -g ${{ secrets.GH_PAT }}