name: Check 365 2/2
on:
  schedule:
    - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: chmod +x ./run.bin

      - name: Check Activity
        run: ./run.bin
        env:
          GITHUB_USER: darmiel
          GITHUB_PAT: ${{ secrets.GH_PAT }}
          PUSHOVER_APP_KEY: ${{ secrets.PUSH_APP_KEY }}
          PUSHOVER_RECIPIENT_KEY: ${{ secrets.PUSH_RECIPIENT_KEY }}
          MESSAGE_TEXT: 'I see you are still lazy'